name: Ruby

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  job_test:
    runs-on: ubuntu-latest
    name: Test (Ruby ${{ matrix.ruby }})
    strategy:
      matrix:
        ruby:
          - '3.2.0'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }} # Not needed with a .ruby-version file, but we want to build multiple versions.
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run the default rake task
      run: bundle exec rake
